import os

class Config:
  SECRET_KEY=os.environ.get('SECRET_KEY')
  SQLALCHEMY_TRACK_MODIFICATIONS=False
  SQLALCHEMY_DATABASE_URI=os.environ.get('DATABASE_URL')
  SQLALCHEMY_ECHO=True
  ACCESS_KEY_ID=os.environ.get("ACCESS_KEY_ID")
  ACCESS_SECRET_KEY=os.environ.get("ACCESS_SECRET_KEY")
