"""change names

Revision ID: 2c2fa009b1e0
Revises: 8aa801a89789
Create Date: 2021-02-13 15:19:29.020671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c2fa009b1e0'
down_revision = '8aa801a89789'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('pictures')
    op.add_column('images', sa.Column('URL', sa.String(), nullable=False))
    op.drop_column('images', 'content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('images', 'URL')
    op.create_table('pictures',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('URL', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('player_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name='pictures_player_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='pictures_pkey')
    )
    op.drop_table('videos')
    # ### end Alembic commands ###
