"""update x and y video table

Revision ID: 3300b9814662
Revises: 8fe81afc3e6d
Create Date: 2021-04-05 20:12:46.768983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3300b9814662'
down_revision = '8fe81afc3e6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('x', sa.String(), nullable=True))
    op.add_column('videos', sa.Column('y', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'y')
    op.drop_column('videos', 'x')
    # ### end Alembic commands ###
