"""added help

Revision ID: 1782ff370d22
Revises: f7c3cadb2fad
Create Date: 2021-04-21 18:33:14.120320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1782ff370d22'
down_revision = 'f7c3cadb2fad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('stopHelp', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'stopHelp')
    # ### end Alembic commands ###
