"""update to videos

Revision ID: 9a179ca5da78
Revises: 6d646d5642ee
Create Date: 2021-02-17 12:48:11.469335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a179ca5da78'
down_revision = '6d646d5642ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('content_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'content_type')
    # ### end Alembic commands ###
